// Generated by CoffeeScript 1.10.0
(function() {
  var argv, fs, inStream, outStream, tokenRules;

  fs = require('fs');

  tokenRules = function(tokenrules) {
    if (tokenrules === "built-in") {
      return require("../defines/tokens");
    } else {
      return require(tokenrules);
    }
  };

  inStream = function(infile) {
    if (infile === "stdin") {
      return process.stdin;
    } else {
      return fs.createReadStream(infile);
    }
  };

  outStream = function(outfile) {
    if (outfile = "stdout") {
      return process.stdout;
    } else {
      return fs.createWriteStream(outfile);
    }
  };

  argv = require('yargs').usage("Usage: $0 [options]")["default"]('i', 'stdin').alias('i', 'in').describe('i', "Input file")["default"]('o', 'stdout').alias('o', 'out').describe('o', "Output file")["default"]('t', 'built-in').alias('t', 'token-rules').describe('t', "File with token rules").boolean('b').alias('b', 'beautify').describe('b', "Beautify output (NOTE: Destroys JSON lines format)").help('h').alias('h', 'help').epilog("Copyright 2016").argv;

  module.exports = {
    instrm: inStream(argv.i),
    outstrm: outStream(argv.o),
    tokenrules: tokenRules(argv.t),
    beautify: argv.b
  };

}).call(this);
