// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    createExprArg: function(value, type, line, column) {
      return {
        type: type,
        line: line,
        column: column,
        value: value
      };
    },
    createExpr: function(line, column, origin, args) {
      return {
        type: "EXPR",
        origin: origin,
        starts: {
          line: line,
          column: column
        },
        ends: null,
        args: args != null ? args : []
      };
    },
    addExprArg: function(expr, value, type, line, column) {
      return {
        type: expr.type,
        origin: expr.origin,
        starts: expr.starts,
        ends: null,
        args: expr.args.concat({
          type: type,
          line: line,
          column: column,
          value: value
        })
      };
    },
    addSubExpression: function(expr, subexpression) {
      return {
        type: expr.type,
        origin: expr.origin,
        starts: expr.starts,
        ends: null,
        args: expr.args.concat(subexpression)
      };
    },
    endExpr: function(expr, line, column) {
      return {
        type: expr.type,
        origin: expr.origin,
        starts: expr.starts,
        ends: {
          line: line,
          column: column
        },
        args: expr.args
      };
    }
  };

}).call(this);
